# Generated by Django 5.0.1 on 2024-02-05 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0009_comment_delete_blog_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_comment', models.CharField(max_length=500)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblogs.blog_post')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
